# Generated by Django 3.2.14 on 2022-10-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
