# Generated by Django 3.2.14 on 2022-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
