# Generated by Django 3.2.14 on 2022-10-15 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_donor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('don', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donor')),
            ],
        ),
    ]
