# Generated by Django 3.2.14 on 2022-10-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='medical_certificate',
            field=models.FileField(upload_to='images/', verbose_name='medical_certificate'),
        ),
    ]
