# Generated by Django 3.2.14 on 2022-10-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_donor_medical_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, verbose_name='fname')),
                ('lname', models.CharField(max_length=100, verbose_name='lname')),
                ('DOB', models.DateField(max_length=100, verbose_name='dob')),
                ('gender', models.CharField(max_length=100, verbose_name='gender')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('ph_no', models.CharField(max_length=100, verbose_name='phn_no')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
