# Generated by Django 3.2.14 on 2022-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
