# Generated by Django 3.2.14 on 2022-10-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('date', models.DateField(max_length=100, verbose_name='date')),
                ('time', models.TimeField(max_length=100, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=100, verbose_name='sub')),
                ('msg', models.CharField(max_length=100, verbose_name='msg')),
                ('reply', models.CharField(max_length=100, verbose_name='reply')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
