# Generated by Django 3.2.14 on 2022-10-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_complaints_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosp_complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=100, verbose_name='sub')),
                ('msg', models.CharField(max_length=100, verbose_name='msg')),
                ('reply', models.CharField(max_length=100, verbose_name='reply')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='donor_complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=100, verbose_name='sub')),
                ('msg', models.CharField(max_length=100, verbose_name='msg')),
                ('reply', models.CharField(max_length=100, verbose_name='reply')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
