# Generated by Django 3.2.14 on 2022-10-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_donor_complaints_hosp_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_complaints',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donor'),
        ),
    ]
