# Generated by Django 3.2.14 on 2022-10-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_donor_complaints_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosp_complaints',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hospital'),
        ),
    ]
