# Generated by Django 3.2.14 on 2022-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_hosp_complaints_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(max_length=100, verbose_name='time'),
        ),
    ]
